### PR TITLE
Fix message display functions to work better

### PR DESCRIPTION
**Pull request by avelitj12**
Also change music to more water-level style rendition

### CODE REVIEW

**Comment by cmavelis** [comment]
guessing based on file extension -- should these `.tmp` files be checked in?

**Comment by cmavelis** [comment]
I agree on the music, I like this track better for the theme.

One thing I would change is make the "Start" button show immediately after Game Over, so you don't have to wait to try again

**Review by cmavelis — APPROVED** [review]

**Comment by cmavelis** [comment]
ignoring .tmp files, see: https://www.reddit.com/r/godot/comments/16zmfmk/is_it_ok_to_ignore_tmp_files_from_git/

**Comment by avelitj12** [comment]
I'll make an issue to fine tune the game over cycle, or at least how it's used. We could have it show for half the time or something

**Pull request merged**
