### PR TITLE
Add new player art, remove placeholders

### LINKED ISSUE #9: Player character sprite art

### PR DESCRIPTION
**Pull request by avelitj12**
https://github.com/Aveli-games/flappy-fish/assets/118833456/a72261ac-c9dd-4d4a-80bc-a362ce4c9837

### CODE REVIEW

**Comment by cmavelis** [comment]
looks kinda blue in the clip compared to the sprite. Does it look like that locally too?

**Comment by avelitj12** [comment]
> looks kinda blue in the clip compared to the sprite. Does it look like that locally too?

Now that you mention it, it looks tinted the color of the sky in main but not in player. Will look into it

**Comment by avelitj12** [comment]
Fixed. Also, check out these sick moves (don't mind the cursor sitting there the whole time)

https://github.com/Aveli-games/flappy-fish/assets/118833456/1742c320-13ab-4bb3-b218-faf1f8358e10

**Review by cmavelis — APPROVED** [review]
dang that's a nice goldfish

**Pull request merged**
